### PR TITLE
Add continuous integration

### PR DESCRIPTION
**Pull request by nlamirault**
Add CircleCI for continuous integration. See [1] for an example, with same error on issue [2].

[1] : https://circleci.com/gh/nlamirault/risno/5
[2] : https://github.com/pgrange/risno/issues/30

### CODE REVIEW

**Comment by nlamirault** [comment]
See : https://circleci.com/gh/nlamirault/risno/14

**Comment by pgrange** [comment]
Did you see this warning on circle ci ? 

Warning: circle.yml specified cache directory: /home/ubuntu/docker but it does not exist

**Comment by pgrange** [comment]
@nlamirault is there a way to sign up to circle ci without giving them write access on my github repos ? No way I give them this authorization !

**Comment by nlamirault** [comment]
No. 
https://circleci.com/docs/github-permissions

**Comment by pgrange** [comment]
That's crap. Docker hub asks for the same permissions with the same reason : "github coarse grain permissions". 

But at least docker hub lets you do the actions manually if you don't want to give them open bar to your github. And this actions are not so hard to do for grown up. 

Circle CI won't even let me create an account without all permissions.

I will not use such a tool. Sorry.

**Pull request closed without merging**
